---
- hosts: localhost
  remote_user: root
  roles:
    - { role: base, tags: ['base'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: kmscon, tags: ['kmscon'] }
    - { role: gui, tags: ['gui'] }
    - { role: input, tags: ['input'] }
    - { role: keyring, tags: ['keyring'] }
    - { role: sound, tags: ['sound'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: editors, tags: ['editors'] }
    - { role: utilities, tags: ['utilities'] }
    - { role: dns, tags: ['dns'] }
    - { role: passwordmanager, tags: ['passwordmanager'] }

  vars_prompt:
    - name: user_password
      prompt: input user password
      private: yes
      confirm: yes
    - name: user_github_token
      prompt: input github token (for regist pubkey)
      private: yes
