---
- hosts: kamo3_work
  remote_user: root
  gather_facts: no

  roles:
    - { role: debug, tags: ["never", "debug"] }
    - { role: init, tags: ["never", "init"] }
    - { role: packagemanager/yay, tags: ["yay"] }
    - { role: cui/shell, tags: ["shell"] }
    - { role: gui/displayserver, tags: ["gui","displayserver"] }
