---
- hosts: kamo3_work
  remote_user: "{{user.name}}"
  become: true
  gather_facts: no

  roles:
    - { role: debug, tags: ["never", "debug"] }
    - { role: init, tags: ["never", "init"] }
    - { role: packagemanager/yay, tags: ["yay"] }
    - { role: cui/shell, tags: ["shell"] }
    - { role: texteditor/neovim, tags: ["texteditor", "neovim"] }
    - { role: gui/displayserver, tags: ["gui", "displayserver"] }
    - { role: gui/displaymanager, tags: ["gui", "displaymanager"] }
    - { role: gui/windowmanager, tags: ["gui", "windowmanager"] }
    - { role: gui/fonts, tags: ["gui", "fonts"] }
    - { role: inputmethod/fcitx, tags: ["inputmethod", "fcitx"] }
    - { role: audio/pulseaudio, tags: ["audio", "pulseaudio"] }
    - { role: network/ntp, tags: ["network", "ntp"] }
    - { role: development/vscode, tags: ["development", "vscode"] }
    - { role: development/docker, tags: ["development", "docker"] }
    - { role: development/virtualbox, tags: ["development", "virtualbox"] }
    - { role: development/git, tags: ["development", "git"] }
    - { role: internet/firefox, tags: ["internet", "firefox"] }
    - { role: internet/chromium, tags: ["internet", "chromium"] }
    - { role: terminal/alacritty, tags: ["terminal", "alacritty"] }
    - {
        role: filesystem/snapper,
        tags: ["filesystem", "snapper", "excludeChroot"],
      }
    - { role: security/keepassxc, tags: ["security", "keepassxc"] }
    - { role: security/authy, tags: ["security", "authy"] }
    - {
        role: gui/compositmanager/compton,
        tags: ["compositmanager", "compton"],
      }
    - { role: gui/launcher/rofi, tags: ["launcher", "rofi"] }
    - { role: gui/statusbar/polybar, tags: ["statusbar", "polybar"] }
    - { role: terminal/tmux, tags: ["terminal", "tmux"] }
    - { role: cui/fzf, tags: ["cui", "fzf"] }
    - { role: cui/powerline, tags: ["cui", "powerline"] }
    - { role: security/gnome-keyring, tags: ["security", "gnome-keyring"] }
    - { role: filesystem/dropbox, tags: ["filesystem", "dropbox"] }
    - { role: filesystem/grive, tags: ["filesystem", "grive"] }
