---
- hosts: kamo3_work
  remote_user: "{{user.name}}"
  become: true
  gather_facts: no
  vars_files:
    - vars/kamo3_work/{{ stage }}.yml
    - vars/kamo3_work/common.yml
    - vars/common.yml
  roles:
    - { role: debug, tags: ["never", "debug"] }
    - { role: init, tags: ["never", "init"] }
    - { role: packagemanager/yay, tags: ["yay"] }
    - { role: cui/shell, tags: ["shell"] }
    - { role: cui/utils, tags: ["cui", "utils"] }
    - { role: texteditor/neovim, tags: ["texteditor", "neovim"] }
    - { role: gui/displayserver, tags: ["gui", "displayserver"] }
    - { role: gui/displaymanager, tags: ["gui", "displaymanager"] }
    - { role: gui/windowmanager, tags: ["gui", "windowmanager"] }
    - { role: gui/fonts, tags: ["gui", "fonts"] }
    - { role: inputmethod/fcitx, tags: ["inputmethod", "fcitx"] }
    - { role: audio/pulseaudio, tags: ["audio", "pulseaudio"] }
    - { role: development/vscode, tags: ["development", "vscode"] }
    - { role: development/docker, tags: ["development", "docker"] }
    - { role: development/virtualbox, tags: ["development", "virtualbox"] }
    - { role: development/git, tags: ["development", "git"] }
    - { role: internet/firefox, tags: ["internet", "firefox"] }
    - { role: internet/chromium, tags: ["internet", "chromium"] }
    - { role: internet/googlechrome, tags: ["internet", "googlechrome"] }
    - { role: terminal/alacritty, tags: ["terminal", "alacritty"] }
    - {
        role: filesystem/snapper,
        tags: ["filesystem", "snapper", "excludeChroot"],
      }
    - { role: security/keepassxc, tags: ["security", "keepassxc"] }
    - { role: security/authy, tags: ["security", "authy"] }
    - { role: gui/compositmanager/picom, tags: ["compositmanager", "picom"] }
    - { role: gui/launcher/rofi, tags: ["launcher", "rofi"] }
    - { role: gui/statusbar/polybar, tags: ["statusbar", "polybar"] }
    - { role: terminal/tmux, tags: ["terminal", "tmux"] }
    - { role: cui/fzf, tags: ["cui", "fzf"] }
    - { role: cui/powerline, tags: ["cui", "powerline"] }
    - { role: security/gnome-keyring, tags: ["security", "gnome-keyring"] }
    - { role: filesystem/dropbox, tags: ["filesystem", "dropbox"] }
    - {
        role: filesystem/google-drive-ocamlfuse,
        tags: ["filesystem", "google-drive-ocamlfuse"],
      }
    - { role: video/vlc, tags: ["video", "vlc"] }
    - { role: system, tags: ["system"] }
    - { role: boostnote, tags: ["boostnote"] }
    - { role: qbittorrent, tags: ["qbittorrent"] }
    - { role: printer, tags: ["printer"] }
    - { role: filemanager/thunar, tags: ["filemanager", "thunar"] }
    - { role: pdf/okular, tags: ["pdf", "okular"] }
    - { role: archiver/unarchiver, tags: ["archiver", "unarchiver"] }
    - { role: archiver/common, tags: ["archiver", "common"] }
    - { role: archiver/xarchiver, tags: ["archiver", "xarchiver"] }
    - { role: remmina, tags: ["remmina"] }
    - { role: timesyncd, tags: ["timesyncd"] }
    - { role: numlockontty, tags: ["numlockontty"] }
    - { role: libreoffice, tags: ["libreoffice"]}
    - { role: feh, tags: ["feh"]}
    - { role: internet/profileSyncDaemon, tags: ["profileSyncDaemon"]}
