---
- hosts: kamo3_work
  remote_user: root
  gather_facts: no

  roles:
    - { role: debug, tags: ["never", "debug"] }
    - { role: init, tags: ["never", "init"] }
    - { role: packagemanager/yay, tags: ["yay"] }
    - { role: cui/shell, tags: ["shell"] }
    - { role: gui/displayserver, tags: ["gui", "displayserver"] }
    - { role: gui/displaymanager, tags: ["gui", "displaymanager"] }
    - { role: gui/windowmanager, tags: ["gui", "windowmanager"] }
    - { role: gui/fonts, tags: ["gui", "fonts"] }
    - { role: inputmethod/fcitx, tags: ["inputmethod", "fcitx"] }
    - { role: audio/pulseaudio, tags: ["audio", "pulseaudio"] }
    - { role: network/ntp, tags: ["network", "ntp"] }
    - {
        role: "network/dnscrypt-proxy",
        tags: ["network", "dns", "dnscrypt-proxy"],
      }
    - { role: network/dnsmasq, tags: ["network", "dns", "dnsmasq"] }
    - { role: development/vscode, tags: ["development", "vscode"] }
    - { role: development/docker, tags: ["development", "docker"] }
    - { role: development/virtualbox, tags: ["development", "virtualbox"] }
    - { role: internet/firefox, tags: ["internet", "firefox"] }
    - { role: terminal/alacritty, tags: ["terminal", "alacritty"] }
