---
- name: import pgp key
  become: yes
  become_user: '{{ user.name }}'
  command: gpg --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
- name: install dropbox
  become: yes
  become_user: '{{ user.name }}'
  aur:
    name: dropbox
