---
- name: lightdm
  block:
    - name: install lightdm
      pacman:
        name: lightdm
    - name: configure run numlockx
      lineinfile: 
        path: /etc/lightdm/lightdm.conf
        regexp: '^\s*greeter-setup-script\s*=\s*.*'
        line: 'greeter-setup-script=/usr/bin/numlockx on'
        insertafter: '\[Seat:\*\]'
    - name: enable lightdm
      service:
        name: lightdm.service
        enabled: yes
  when: '"lightdm" in gui.displaymanager.use'