---
- name: install rofi
  pacman:
    name: rofi
- name: install polybar
  pacman:
    name: polybar
- name: install compton
  pacman:
    name: compton
- name: install dex
  pacman:
    name: dex
- name: install feh
  pacman:
    name: feh
