---
kernel:
  version: 53
  ucode: intel

hostname: kamo3_work
bootloader:
  loader:
    default: manjaro
  entries:
    - title: manjaro
      filename: manjaro.conf
      linux: /vmlinuz-5.3-x86_64
      initrds:
        - /{{kernel.ucode}}-ucode.img
        - /initramfs-5.3-x86_64.img
      options: root=PARTLABEL=manjaro rootflags=subvol=@ rw

    - title: manjaro (fallback)
      filename: manjaro_fallback.conf
      linux: /vmlinuz-5.3-x86_64
      initrds:
        - /{{kernel.ucode}}-ucode.img
        - /initramfs-5.3-x86_64-fallback.img
      options: root=PARTLABEL=manjaro rootflags=subvol=@ rw

gui:
  displayserver:
    use:
      - xorg
  displaymanager:
    use:
      - lightdm
    greeter:
      use:
        - lightdm-webkit-theme-litarvan
  windowmanager:
    use:
      - i3-gaps
  
network:
  dns:
    dnscrypt:
      port: 15353
      servers:
        - cloudflare
        - google
      forwards:
        - name: mikamosrv.org
          ip: 192.168.100.40
    dnsmasq:
      host: 127.0.0.1
      upstream:
        host: 127.0.0.1
        port: 15353