---
- include: packagemanager.yml
  tags:
    - packagemanager
- include: base_package.yml
  tags:
    - base_package
- include: user.yml
  tags:
    - user
- include: shell.yml
  tags:
    - shell
- include: sshd.yml
  tags:
    - sshd
- include: virtualbox_guest.yml
  tags:
    - virtualbox_guest
  when:
    - ansible_facts['virtualization_role'] == "guest"
    - ansible_facts['virtualization_type'] == "virtualbox"
