---
- name: user config
  block:
    - name: add user
      user:
        name: '{{ user.name }}'
        append: yes
        groups:
          - wheel
        uid: '{{ user.uid }}'
        shell: '{{ user.shell }}'
        password: "{{ user_password | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
    - name: set sudo config
      template:
        src: sudoers.j2
        dest: /etc/sudoers
        mode: '440'
        owner: root
        group: root

    - name: read ssh pubkey to github
      shell: cat /home/{{user.name}}/.ssh/id_rsa.pub
      register: ssh_pub_key

    - name: add pubkey to github
      github_key:
        token: '{{ user_github_token }}'
        pubkey: '{{ ssh_pub_key.stdout }}'
        name: '{{ user.github.pubkey_name_pref }}-{{ansible_date_time.iso8601}}'
      when: user_github_token | length > 0

    - name: check if fingerprint is registered
      shell: grep -c ^github.com /home/{{user.name}}/.ssh/known_hosts
      register: ssh_github_exist_in_knowhost
      failed_when: False
      changed_when: False

    - name: regist fingerprint
      block:
        - name: get fingerprint for github.com
          shell: ssh-keyscan github.com
          register: ssh_fingerprint_github
          changed_when: False

        - name: set fingerprint for github.com to known_hosts
          become: yes
          become_user: '{{user.name}}'
          lineinfile:
            create: yes
            path: /home/{{user.name}}/.ssh/known_hosts
            line: '{{ssh_fingerprint_github.stdout_lines[0]}}'
      when: ssh_github_exist_in_knowhost.rc != 0
  when: user_password | length > 0
