---
- name: install base packages
  pacman:
    name: 
      - base
      - base-devel
      - linux{{ kernel.version.majour }}{{ kernel.version.minor}}
      - linux{{ kernel.version.majour }}{{ kernel.version.minor}}-headers
      - btrfs-progs
      - "{{ kernel.ucode }}-ucode"
      - openssh
