---
- name: install fontconfig
  pacman:
    name: fontconfig
- name: install fonts (pacman)
  pacman:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
- name: install fonts (aur)
  become: yes
  become_user: '{{ user.name }}'
  aur:
    use: '{{ aur.helper }}'
    name:
      - nerd-fonts-ricty
      - ttf-cica
- name: configure noto
  file:
    src: /etc/fonts/conf.avail/{{ item }}
    dest: /etc/fonts/conf.d/{{ item }}
    state: link
  with_items:
    - 66-noto-mono.conf
    - 66-noto-sans.conf
    - 66-noto-serif.conf
    - 70-noto-cjk.conf

- name: configure alias for monospace fonts
  copy:
    src: local.conf
    dest: /etc/fonts/local.conf
    mode: '0644'
